### ISSUE TITLE
is there a linux version?

### ISSUE THREAD

**Issue by infamedavid** [stellare-modular/vcv-rack#15]
is there a linux version? where could I found the source to compile?
thanks!

**Comment by infamedavid** [comment]
sorry , my bad I fuund it here
https://github.com/stellare-modular/vcv-rack/releases/download/0.6.0/StellareModular-0.6.0-all.zip

**Comment by stellare-modular** [comment]
Starting with version 0.6.1 this package is available through the Plugin Manager, so getting to the Linux binaries will be done automatically by VCV Rack.
