### ISSUE TITLE
Link - ANY documentation on how to use?

### ISSUE THREAD

**Issue by JeffGreenlee42** [stellare-modular/vcv-rack#7]
This is not necessarily an issue,  More of a question:   is there ANY documentation on the use of the Link module in VCVRack?    I can't find anything here in this Github repository.. No Youtube video .. well.. there is ONE regarding its use with BitWig..  but its kind of useless, because No one is talking and we're supposed to figure it out by just looking at his VCV patch!    Just a small paragraph?   Please?  I cannot figure out how the heck to use the dumb thing!  HOW is it connected to Ableton Link?  There is no input...  How does it sync? How are clients suppose to link to it?  Why are there just two outputs that are just clock dividers? no 1 to 1 ration?

**Comment by stellare-modular** [comment]
> Is there ANY documentation on the use of the Link module in VCVRack?

You are right, documentation is pretty sparse. The idea was to make it so simple that it doesn't need any documentation :)

> How is it connected to Ableton Link?

As soon as you create it in VCV Rack, the module connects to the Link session running on your local network (both Ethernet or Wi-Fi) or it creates one if no Link session is active.

> How does it sync? How are clients suppose to link to it?

Syncronization is basically the one and only feature provided automatically by Ableton Link protocol. Clients just need to join a Link session to be in sync with it, in Ableton Live this is done by clicking on the Link button in the toolbar, the Stellare Modular Link module does it automatically.

> Why are there just two outputs that are just clock dividers? no 1 to 1 ration?

We felt a 1-1 output wouldn't be that useful as it will trigger on each beat (e.g. once every half a second in a 120BPM session) and usually you need a higher resolution clock.
