### ISSUE TITLE
Turing Machine 0.6.0 not working with audio range clock ?

### ISSUE THREAD

**Issue by davephillips** [stellare-modular/vcv-rack#8]
Fedora 23 Linux
Rack master (0.6.x dev)

Greetings ! I'm testing the latest 0.6.0 release by running Hagen Ueberfuhr's demonstration at https://www.youtube.com/watch?v=InbikxInuKE. Unfortunately the latter part of the demo no longer functions, I'm getting no audio output at all from the 2nd instance of the Machine. I also tried using only that part of his patch on its own, got the same result. Am I missing something or has something crucial changed in the module ?

**Comment by sanderbaan** [comment]
Hey Dave, 

Maybe its because the combined pulse outputs default to AND behaviour, it was actually a bug compared to the hw version. You can change it OR by right clicking on the module ;)

Best
Sander

**Comment by davephillips** [comment]
Hi Sander, Thanks for the quick reply and suggestion. The AND/OR setting made no difference, but I replaced Hagen's use of the Fundamental VCO-1 with the square wave output from the first EvenVCO in his patch. That solved the issue, I'm not sure why. Perhaps a voltage consideration ? I do get some occasional distortion, again I'm not sure why, but now my patch sounds like his demo. Anyway, here's a screenshot of my working patch. :) 
![turingtest1](https://user-images.githubusercontent.com/7815938/38045592-3338aaa6-328b-11e8-901d-0c4645ca9f44.png)
